apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcode-v2-static
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tc2-static-files
      tier: backend
  template:
    metadata:
      labels:
        app: tc2-static-files
        tier: backend
    spec:
      imagePullSecrets:
        - name: docker-regcred
        - name: gitlab-maglev-reg
      volumes:
        - name: nginxlogs
          emptyDir: {}
      containers:
        - name: tc2-static-nginx
          imagePullPolicy: Always
          image: registry.gitlab.com/paperstreet/dogma/transcode-v2:static
          ports:
            - containerPort: 80
              name: tc2-static
          readinessProbe:
            tcpSocket:
              port: tc2-static
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: tc2-static
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: nginxlogs
              mountPath: /var/log/nginx
        - name: nginx-access-logs
          image: busybox
          args: [/bin/sh, -c, 'echo "" > /var/log/nginx/access.log && chmod 0666 /var/log/nginx/access.log && tail -n+1 -f /var/log/nginx/access.log']
          volumeMounts:
            - name: nginxlogs
              mountPath: /var/log/nginx
        - name: nginx-error-logs
          image: busybox
          args: [/bin/sh, -c, 'echo "" > /var/log/nginx/error.log && chmod 0666 /var/log/nginx/error.log && tail -n+1 -f /var/log/nginx/error.log']
          volumeMounts:
            - name: nginxlogs
              mountPath: /var/log/nginx

---
apiVersion: v1
kind: Service
metadata:
  name: tc2-static-srv
spec:
  selector:
    app: tc2-static-files
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: tc2-static
